name: Code quality check

on:
    push:
        branches: [main]

jobs:
    validate:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                jdk-version: ['21','22','23']
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Set up JDK ${{ matrix.jdk-version }}
              uses: actions/setup-java@v4
              with:
                java-version: ${{ matrix.jdk-version }}
                distribution: 'temurin'
                cache: maven

            - name: Build with Maven
              run: mvn --batch-mode --update-snapshots verify

            - name: Run Linter
              run: mvn checkstyle:check

            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@v3