name: Code quality check

on:
    push:
        branches: [docker]

jobs:
    validate:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                jdk-version: ['17','21']
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            
            - name: Start MySQL
              uses: mirromutth/mysql-action@v1.1
              with:
                mysql_root_password: Test@123
                mysql_database: bankappdb

            - name: Run Linter
              run: mvn checkstyle:check
            
            - name: Build with Maven
              run: mvn clean package
            
            - name: Initialize CodeQL
              uses: github/codeql-action/init@v3
              with:
                languages: java

            - name: Autobuild
              uses: github/codeql-action/autobuild@v3

            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@v3