name: DevSecOps Pipeline

on:
    push:
        branches: [docker]

permissions:
  contents: read
  security-events: write

jobs:
    # CI for AI-Bank-APP
    # code-quality:
    #     uses: ./.github/workflows/code-quality.yml
    #     secrets: inherit
    
    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml

    secrets-scan:
        uses: ./.github/workflows/secret-scan.yml
    
    docker-linter:
        uses: ./.github/workflows/docker-linter.yml

    docker-image-build:
        needs: [dependency-scan, secrets-scan, docker-linter]
        uses: ./.github/workflows/docker-build-and-push.yml
        secrets: inherit

    image-scan:
        needs: [docker-image-build]
        uses: ./.github/workflows/image-scan.yml
        secrets: inherit

    # deploy-to-server:
    #     needs: [image-scan]
    #     uses: ./.github/workflows/deploy-to-server.yml
    #     secrets: inherit

    
    
