name: Docker linter

on:
    # push:
    #     branches: [docker]
    workflow_call:

jobs:
    validate-Dockerfile:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Validate Dockerfile
          uses: hadolint/hadolint-action@v3.1.0
          with:
            dockerfile: Dockerfile.multistage
